using Microsoft.Extensions.AI;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Agents;
using Microsoft.SemanticKernel.Connectors.AzureOpenAI;
using OpenAI.Chat;
using System.ComponentModel;

namespace DurableMultiAgentWorkflowSample.Workflow.Agents;
internal class AgentDefinitions(Kernel kernel)
{
    public static string WriterAgentName = "WriterAgent";
    public static string ReviewerAgentName = "ReviewerAgent";
    public static string ApproverAgentName = "ApproverAgent";

    public Agent CreateWriterAgent()
    {
        return new ChatCompletionAgent
        {
            Name = "WriterAgent",
            Instructions = "You are a writer agent. Your task is to generate creative content based on the provided chat history.",
            Kernel = kernel,
        };
    }

    public Agent CreateReviewerAgent()
    {
        return new ChatCompletionAgent
        {
            Name = "ReviewerAgent",
            Instructions = """
                You are a reviewer agent. Your task is to review and provide feedback on the content generated by the writer agent. 
                If you have no specific issues or improvements to point out, respond only with 'No issues found.
                """,
            Kernel = kernel,
        };
    }

    public Agent CreateApproverAgent()
    {
        return new ChatCompletionAgent
        {
            Name = "ApproverAgent",
            Instructions = """
                You are an approver agent. Your task is to approve or reject the content based on the reviewer's feedback. 
                Set Approved to true if there are no improvements or issues mentioned in the reviewer's comments. 
                Set Approved to false if the reviewer has suggested any improvements or identified any issues.
                """,
            Kernel = kernel,
            Arguments = new(new AzureOpenAIPromptExecutionSettings
            {
                ResponseFormat = typeof(ApproverAgentResponse),
            }),
        };
    }
}

public record ApproverAgentResponse(
    [property: Description("Set to true if there are no improvements or issues in the reviewer's comments. Otherwise, set to false.")]
    bool Approved);
