@DurableMultiAgentWorkflowSample.Workflow_HostAddress = http://localhost:7071
@Id = 7fba38185bde48248c0cf3e9e595652a

POST {{DurableMultiAgentWorkflowSample.Workflow_HostAddress}}/api/Start
Content-Type: application/json

{
  "Message": "JavaScript を書いたことがある人向けの C# 入門記事を書いてください"
}

###
GET {{DurableMultiAgentWorkflowSample.Workflow_HostAddress}}/api/GetWorkflowStatus?instanceId={{Id}}

###
POST {{DurableMultiAgentWorkflowSample.Workflow_HostAddress}}/api/Reply
Content-Type: application/json

{
  "Id": "{{Id}}",
  "Message": "express と ASP.NET Core Minimal API で Hello world を返すような簡単な Web API の例も足してください。C# だからといっていたずらにコード量が増えるわけではないという点をそれとなく訴求したいです。"
}

###
POST {{DurableMultiAgentWorkflowSample.Workflow_HostAddress}}/api/Reply
Content-Type: application/json

{
  "Id": "{{Id}}",
  "Message": "Approve"
}