@DurableMultiAgentWorkflowSampleWorkflow_HostAddress = http://localhost:7071
@Id = 32f27fa9-4a91-430b-aef1-47dcd4784790

POST {{DurableMultiAgentWorkflowSampleWorkflow_HostAddress}}/api/Start
Content-Type: application/json

{
  "Message": "JavaScript を書いたことがある人向けの C# 入門記事を書いてください"
}

###
GET {{DurableMultiAgentWorkflowSampleWorkflow_HostAddress}}/api/GetWorkflowStatus?instanceId={{Id}}

###
POST {{DurableMultiAgentWorkflowSampleWorkflow_HostAddress}}/api/Reply
Content-Type: application/json

{
  "Id": "{{Id}}",
  "Message": "express と ASP.NET Core Minimal API で Hello world を返すような簡単な Web API の例も足してください。C# だからといっていたずらにコード量が増えるわけではないという点をそれとなく訴求したいです。"
}

###
POST {{DurableMultiAgentWorkflowSampleWorkflow_HostAddress}}/api/Reply
Content-Type: application/json

{
  "Id": "{{Id}}",
  "Message": "Approve"
}